/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author DIL-SOFT 02
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        buttonclose = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        dashbord = new javax.swing.JPanel();
        buttonadmin = new javax.swing.JPanel();
        admin = new javax.swing.JLabel();
        buttonuser = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Systemname = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(5, 10, 46));
        Header.setPreferredSize(new java.awt.Dimension(100, 50));
        Header.setLayout(new java.awt.BorderLayout());

        buttonclose.setBackground(new java.awt.Color(5, 10, 46));
        buttonclose.setPreferredSize(new java.awt.Dimension(50, 38));
        buttonclose.setLayout(new java.awt.BorderLayout());

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_25px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        buttonclose.add(close, java.awt.BorderLayout.CENTER);

        Header.add(buttonclose, java.awt.BorderLayout.LINE_END);

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 38));

        dashbord.setBackground(new java.awt.Color(5, 10, 46));
        dashbord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonadmin.setBackground(new java.awt.Color(107, 116, 144));
        buttonadmin.setPreferredSize(new java.awt.Dimension(200, 240));
        buttonadmin.setLayout(new java.awt.BorderLayout());

        admin.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/find_user_male_127px.png"))); // NOI18N
        admin.setText("Admin Login");
        admin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        admin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminMouseExited(evt);
            }
        });
        buttonadmin.add(admin, java.awt.BorderLayout.CENTER);

        dashbord.add(buttonadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 35, -1, -1));

        buttonuser.setBackground(new java.awt.Color(107, 116, 144));
        buttonuser.setPreferredSize(new java.awt.Dimension(200, 240));
        buttonuser.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/worker_127px.png"))); // NOI18N
        jLabel3.setText("User Login");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        buttonuser.add(jLabel3, java.awt.BorderLayout.CENTER);

        dashbord.add(buttonuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 35, -1, -1));

        getContentPane().add(dashbord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 187, 480, 310));

        Systemname.setBackground(new java.awt.Color(32, 48, 90));
        Systemname.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Stock Management System");
        Systemname.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 82, -1, -1));

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Spare Part");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 59));
        Systemname.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 17, 252, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bus005.gif"))); // NOI18N
        Systemname.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 0, 189, 80));

        getContentPane().add(Systemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, 490, 150));

        setSize(new java.awt.Dimension(475, 497));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
       changecolor(buttonclose, new Color(232, 17, 35));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        changecolor(buttonclose, new Color(5, 10, 46));
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseEntered
        changecolor(buttonadmin, new Color(181, 185, 199));
    }//GEN-LAST:event_adminMouseEntered

    private void adminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseExited
        changecolor(buttonadmin, new Color(107,116,144));
    }//GEN-LAST:event_adminMouseExited

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        Admin_Login E =new Admin_Login();
        E.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminMouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        changecolor(buttonuser, new Color(181, 185, 199));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        changecolor(buttonuser, new Color(107,116,144));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        User_Login E =new User_Login();
        E.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Systemname;
    private javax.swing.JLabel admin;
    private javax.swing.JPanel buttonadmin;
    private javax.swing.JPanel buttonclose;
    private javax.swing.JPanel buttonuser;
    private javax.swing.JLabel close;
    private javax.swing.JPanel dashbord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
