/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DIL-SOFT 02
 */
public class Spare_Parts_Details extends javax.swing.JFrame {

    /**
     * Creates new form SparePart_Stock_Details
     */
    
    boolean a = true;
    
    public Spare_Parts_Details() {
        initComponents();
        dashbordview.setBackground(new Color(0,0,0,200));
        
        fillTable();
        
       SqlConnection();
        
    }
    
    //Database connection
    public Connection SqlConnection(){
        
        Connection conn =  null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Stock_System","root","");
            //JOptionPane.showMessageDialog(null, "Mysql connected Sucessfully");
            return conn;
            
        } catch (Exception e) {
                       JOptionPane.showMessageDialog(null, "Mysql connected fail");
            return null;
        }
    }
    
    String photopath = "";
        //Resize Image
    public ImageIcon resetImageSize(String photopath, byte[] photo)
    {
        ImageIcon myphoto = null;
        
        if(photopath != null){
            myphoto = new ImageIcon(photopath);
        }
        else{
            myphoto = new ImageIcon(photo);
        }
        
        Image img = myphoto .getImage();
        Image img1 = img.getScaledInstance(lbl_image.getHeight(), lbl_image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ph = new ImageIcon(img1);
        return ph;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        Iconminmaxclose = new javax.swing.JPanel();
        Buttonclose = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        ButtonMax = new javax.swing.JPanel();
        Fullmax = new javax.swing.JLabel();
        ButtonMin = new javax.swing.JPanel();
        Minimize = new javax.swing.JLabel();
        Heading = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        MenuIcon = new javax.swing.JPanel();
        linehome = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        buttonhome = new javax.swing.JLabel();
        linehidemenu = new javax.swing.JPanel();
        hidemenu = new javax.swing.JPanel();
        buttonhidemenu = new javax.swing.JLabel();
        menuhide = new javax.swing.JPanel();
        buttontec_details = new javax.swing.JPanel();
        tec_details = new javax.swing.JLabel();
        buttonstock_details = new javax.swing.JPanel();
        stock_details = new javax.swing.JLabel();
        buttonstocktable_details = new javax.swing.JPanel();
        stocktable_details = new javax.swing.JLabel();
        dashbordview = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextSpare_ID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextSpare_Name = new javax.swing.JTextField();
        lbl_image = new javax.swing.JLabel();
        butt_Choose_image = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Bnt_delete = new javax.swing.JButton();
        Bntt_add = new javax.swing.JButton();
        Bnt_update = new javax.swing.JButton();
        buttontsearch = new javax.swing.JPanel();
        Ssearch = new javax.swing.JLabel();
        jText_Search = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1_Spare = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jTextSpare_qut = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(5, 10, 46));
        Header.setPreferredSize(new java.awt.Dimension(350, 50));
        Header.setLayout(new java.awt.BorderLayout());

        Iconminmaxclose.setBackground(new java.awt.Color(5, 10, 46));
        Iconminmaxclose.setPreferredSize(new java.awt.Dimension(150, 50));
        Iconminmaxclose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buttonclose.setBackground(new java.awt.Color(5, 10, 46));
        Buttonclose.setLayout(new java.awt.BorderLayout());

        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_25px.png"))); // NOI18N
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseMouseExited(evt);
            }
        });
        Buttonclose.add(Close, java.awt.BorderLayout.CENTER);

        Iconminmaxclose.add(Buttonclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        ButtonMax.setBackground(new java.awt.Color(5, 10, 46));
        ButtonMax.setPreferredSize(new java.awt.Dimension(50, 50));
        ButtonMax.setLayout(new java.awt.BorderLayout());

        Fullmax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fullmax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/full_screen_25px.png"))); // NOI18N
        Fullmax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FullmaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FullmaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FullmaxMouseExited(evt);
            }
        });
        ButtonMax.add(Fullmax, java.awt.BorderLayout.CENTER);

        Iconminmaxclose.add(ButtonMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        ButtonMin.setBackground(new java.awt.Color(5, 10, 46));
        ButtonMin.setLayout(new java.awt.BorderLayout());

        Minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize_window_25px.png"))); // NOI18N
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeMouseExited(evt);
            }
        });
        ButtonMin.add(Minimize, java.awt.BorderLayout.CENTER);

        Iconminmaxclose.add(ButtonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        Header.add(Iconminmaxclose, java.awt.BorderLayout.LINE_END);

        Heading.setBackground(new java.awt.Color(5, 10, 46));
        Heading.setPreferredSize(new java.awt.Dimension(350, 50));
        Heading.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 1, 27)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/maintenance_45px.png"))); // NOI18N
        jLabel8.setText("Spare Part Details");
        Heading.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 290, 40));

        Header.add(Heading, java.awt.BorderLayout.LINE_START);

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 50));

        menu.setPreferredSize(new java.awt.Dimension(310, 630));
        menu.setLayout(new java.awt.BorderLayout());

        MenuIcon.setBackground(new java.awt.Color(5, 10, 46));
        MenuIcon.setPreferredSize(new java.awt.Dimension(65, 630));
        MenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linehome.setBackground(new java.awt.Color(5, 10, 46));
        linehome.setPreferredSize(new java.awt.Dimension(65, 5));

        javax.swing.GroupLayout linehomeLayout = new javax.swing.GroupLayout(linehome);
        linehome.setLayout(linehomeLayout);
        linehomeLayout.setHorizontalGroup(
            linehomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        linehomeLayout.setVerticalGroup(
            linehomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(linehome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 65, 5));

        home.setBackground(new java.awt.Color(5, 10, 46));
        home.setPreferredSize(new java.awt.Dimension(65, 65));
        home.setLayout(new java.awt.BorderLayout());

        buttonhome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_30px.png"))); // NOI18N
        buttonhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhomeMouseExited(evt);
            }
        });
        home.add(buttonhome, java.awt.BorderLayout.CENTER);

        MenuIcon.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 65, 65));

        linehidemenu.setBackground(new java.awt.Color(5, 10, 46));
        linehidemenu.setPreferredSize(new java.awt.Dimension(65, 5));

        javax.swing.GroupLayout linehidemenuLayout = new javax.swing.GroupLayout(linehidemenu);
        linehidemenu.setLayout(linehidemenuLayout);
        linehidemenuLayout.setHorizontalGroup(
            linehidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        linehidemenuLayout.setVerticalGroup(
            linehidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(linehidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 65, 5));

        hidemenu.setBackground(new java.awt.Color(5, 10, 46));
        hidemenu.setPreferredSize(new java.awt.Dimension(65, 65));
        hidemenu.setLayout(new java.awt.BorderLayout());

        buttonhidemenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonhidemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_30px.png"))); // NOI18N
        buttonhidemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseExited(evt);
            }
        });
        hidemenu.add(buttonhidemenu, java.awt.BorderLayout.CENTER);

        MenuIcon.add(hidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 65, 65));

        menu.add(MenuIcon, java.awt.BorderLayout.LINE_START);

        menuhide.setBackground(new java.awt.Color(25, 29, 74));

        buttontec_details.setBackground(new java.awt.Color(25, 29, 74));
        buttontec_details.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 10, 46), 1, true));
        buttontec_details.setPreferredSize(new java.awt.Dimension(170, 47));

        tec_details.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        tec_details.setForeground(new java.awt.Color(255, 255, 255));
        tec_details.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tec_details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/workers_45px.png"))); // NOI18N
        tec_details.setText("Technician Details");
        tec_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tec_detailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tec_detailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tec_detailsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttontec_detailsLayout = new javax.swing.GroupLayout(buttontec_details);
        buttontec_details.setLayout(buttontec_detailsLayout);
        buttontec_detailsLayout.setHorizontalGroup(
            buttontec_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tec_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        buttontec_detailsLayout.setVerticalGroup(
            buttontec_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttontec_detailsLayout.createSequentialGroup()
                .addComponent(tec_details)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        buttonstock_details.setBackground(new java.awt.Color(25, 29, 74));
        buttonstock_details.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 10, 46), 1, true));

        stock_details.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        stock_details.setForeground(new java.awt.Color(255, 255, 255));
        stock_details.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stock_details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/warehouse_45px.png"))); // NOI18N
        stock_details.setText("Stock Details");
        stock_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stock_detailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stock_detailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stock_detailsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttonstock_detailsLayout = new javax.swing.GroupLayout(buttonstock_details);
        buttonstock_details.setLayout(buttonstock_detailsLayout);
        buttonstock_detailsLayout.setHorizontalGroup(
            buttonstock_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonstock_detailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stock_details, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        buttonstock_detailsLayout.setVerticalGroup(
            buttonstock_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonstock_detailsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(stock_details))
        );

        buttonstocktable_details.setBackground(new java.awt.Color(25, 29, 74));
        buttonstocktable_details.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 10, 46), 1, true));

        stocktable_details.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        stocktable_details.setForeground(new java.awt.Color(255, 255, 255));
        stocktable_details.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stocktable_details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/view_45px.png"))); // NOI18N
        stocktable_details.setText("Stock Table Details");
        stocktable_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stocktable_detailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stocktable_detailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stocktable_detailsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttonstocktable_detailsLayout = new javax.swing.GroupLayout(buttonstocktable_details);
        buttonstocktable_details.setLayout(buttonstocktable_detailsLayout);
        buttonstocktable_detailsLayout.setHorizontalGroup(
            buttonstocktable_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(stocktable_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        buttonstocktable_detailsLayout.setVerticalGroup(
            buttonstocktable_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonstocktable_detailsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(stocktable_details))
        );

        javax.swing.GroupLayout menuhideLayout = new javax.swing.GroupLayout(menuhide);
        menuhide.setLayout(menuhideLayout);
        menuhideLayout.setHorizontalGroup(
            menuhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonstock_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttontec_details, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
            .addComponent(buttonstocktable_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuhideLayout.setVerticalGroup(
            menuhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuhideLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(buttontec_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(buttonstock_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(buttonstocktable_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        menu.add(menuhide, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 290, 580));

        dashbordview.setBackground(new java.awt.Color(0, 0, 0));
        dashbordview.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dashbordview.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Image:");
        dashbordview.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 130, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Spare Part ID:");
        dashbordview.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 100, 30));

        jTextSpare_ID.setBackground(new java.awt.Color(55, 55, 55));
        jTextSpare_ID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextSpare_ID.setForeground(new java.awt.Color(255, 255, 255));
        jTextSpare_ID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextSpare_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextSpare_ID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextSpare_ID.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTextSpare_ID.setSelectionColor(new java.awt.Color(55, 55, 55));
        dashbordview.add(jTextSpare_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 260, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Spare Part Name:");
        dashbordview.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 130, 30));

        jTextSpare_Name.setBackground(new java.awt.Color(55, 55, 55));
        jTextSpare_Name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextSpare_Name.setForeground(new java.awt.Color(255, 255, 255));
        jTextSpare_Name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextSpare_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextSpare_Name.setCaretColor(new java.awt.Color(55, 55, 55));
        jTextSpare_Name.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTextSpare_Name.setSelectionColor(new java.awt.Color(55, 55, 55));
        dashbordview.add(jTextSpare_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 260, 30));

        lbl_image.setBackground(new java.awt.Color(55, 55, 55));
        lbl_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_image.setOpaque(true);
        dashbordview.add(lbl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 260, 110));

        butt_Choose_image.setBackground(new java.awt.Color(102, 102, 102));
        butt_Choose_image.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        butt_Choose_image.setForeground(new java.awt.Color(255, 255, 255));
        butt_Choose_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image_file_button.png"))); // NOI18N
        butt_Choose_image.setText("Choose Image");
        butt_Choose_image.setBorder(null);
        butt_Choose_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_Choose_imageActionPerformed(evt);
            }
        });
        dashbordview.add(butt_Choose_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 160, 30));
        dashbordview.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 260, 10));
        dashbordview.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 260, 10));

        Bnt_delete.setBackground(new java.awt.Color(102, 102, 102));
        Bnt_delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Bnt_delete.setForeground(new java.awt.Color(255, 255, 255));
        Bnt_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button_delete-cute.png"))); // NOI18N
        Bnt_delete.setText("Delete");
        Bnt_delete.setBorder(null);
        Bnt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_deleteActionPerformed(evt);
            }
        });
        dashbordview.add(Bnt_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 130, 40));

        Bntt_add.setBackground(new java.awt.Color(102, 102, 102));
        Bntt_add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Bntt_add.setForeground(new java.awt.Color(255, 255, 255));
        Bntt_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button_add-cute.png"))); // NOI18N
        Bntt_add.setText("Add");
        Bntt_add.setBorder(null);
        Bntt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bntt_addActionPerformed(evt);
            }
        });
        dashbordview.add(Bntt_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 130, 40));

        Bnt_update.setBackground(new java.awt.Color(102, 102, 102));
        Bnt_update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Bnt_update.setForeground(new java.awt.Color(255, 255, 255));
        Bnt_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button_update-cute.png"))); // NOI18N
        Bnt_update.setText("Update");
        Bnt_update.setBorder(null);
        Bnt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_updateActionPerformed(evt);
            }
        });
        dashbordview.add(Bnt_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 130, 40));

        buttontsearch.setBackground(new java.awt.Color(55, 55, 55));
        buttontsearch.setPreferredSize(new java.awt.Dimension(40, 40));
        buttontsearch.setLayout(new java.awt.BorderLayout());

        Ssearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ssearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_20px.png"))); // NOI18N
        Ssearch.setPreferredSize(new java.awt.Dimension(30, 30));
        Ssearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SsearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SsearchMouseExited(evt);
            }
        });
        buttontsearch.add(Ssearch, java.awt.BorderLayout.LINE_START);

        jText_Search.setBackground(new java.awt.Color(55, 55, 55));
        jText_Search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jText_Search.setForeground(new java.awt.Color(255, 255, 255));
        jText_Search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jText_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jText_SearchKeyPressed(evt);
            }
        });
        buttontsearch.add(jText_Search, java.awt.BorderLayout.CENTER);

        dashbordview.add(buttontsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 280, 30));

        jScrollPane2.setBackground(new java.awt.Color(55, 55, 55));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTable1_Spare.setAutoCreateRowSorter(true);
        jTable1_Spare.setBackground(new java.awt.Color(55, 55, 55));
        jTable1_Spare.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 55, 55)));
        jTable1_Spare.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1_Spare.setForeground(new java.awt.Color(255, 255, 255));
        jTable1_Spare.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Spare Part ID", "Spare Part Name", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1_Spare.setGridColor(new java.awt.Color(55, 55, 55));
        jTable1_Spare.setRowHeight(25);
        jTable1_Spare.setRowMargin(8);
        jTable1_Spare.setSelectionBackground(new java.awt.Color(110, 110, 109));
        jTable1_Spare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_SpareMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1_Spare);

        dashbordview.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 420, 320));
        dashbordview.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 260, -1));
        dashbordview.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 280, 10));
        dashbordview.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 260, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantity:");
        dashbordview.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 70, 30));

        jTextSpare_qut.setBackground(new java.awt.Color(55, 55, 55));
        jTextSpare_qut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextSpare_qut.setForeground(new java.awt.Color(255, 255, 255));
        jTextSpare_qut.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextSpare_qut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextSpare_qut.setCaretColor(new java.awt.Color(55, 55, 55));
        jTextSpare_qut.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTextSpare_qut.setSelectionColor(new java.awt.Color(55, 55, 55));
        dashbordview.add(jTextSpare_qut, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 260, 30));

        getContentPane().add(dashbordview, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 970, 580));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIL-SOFT 02\\Documents\\NetBeansProjects\\Spare Part\\src\\Images\\Image 2.jpg")); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 970, 580));

        setSize(new java.awt.Dimension(1260, 627));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void changercolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    public void clickmenu(JPanel h1, JPanel h2, int numberbool){
       if(numberbool == 1){
           h1.setBackground(new Color(25, 29, 74));
           h2.setBackground(new Color(5, 10, 46));
       } 
       else{
           h1.setBackground(new Color(5, 10, 46));
           h2.setBackground(new Color(25, 29, 74));
       }
    }
    
    
    //method for change image
    public void changeImage (JLabel button, String resourcheimg){
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
        button.setIcon(aimg);
    } 
    
    
    public void hideshow(JPanel menushowhide, boolean dashboard, JLabel button){
        if(dashboard == true){
            menushowhide.setPreferredSize(new Dimension(65, menushowhide.getHeight()));
            changeImage(button,"/Images/menu_30px.png");
        }
        else{
            menushowhide.setPreferredSize(new Dimension(276, menushowhide.getHeight()));
            changeImage(button,"/Images/back_30px.png");
        }
    }
    
    
    
    //Show or add the data to the table
    public ArrayList<SparePartDeatilsBean> retriveData(){
        ArrayList<SparePartDeatilsBean> al=null;
        al=new ArrayList<SparePartDeatilsBean>();
        
        try{
            Connection conn=SqlConnection();
            String qry="Select * from Spare_Part";
            Statement st=conn.createStatement();
            ResultSet rs= st.executeQuery(qry);
            SparePartDeatilsBean Spare;
            while(rs.next()){
                Spare= new SparePartDeatilsBean(rs.getInt(1), rs.getString(2),rs.getInt(3),rs.getBytes(4));
                al.add(Spare);
            }
        }catch(Exception e){
            System.out.println("Error in retriveData method:"+e);
            
        }
       return al; 
    }
    
    public void fillTable(){
        ArrayList<SparePartDeatilsBean> al = retriveData();
        DefaultTableModel model=(DefaultTableModel)jTable1_Spare.getModel();
        model.setRowCount(0);
        
        Object[] row = new Object[3];
        for(int i=0; i<al.size(); i++){
            row[0]=al.get(i).getId();
            row[1]=al.get(i).getName();
            row[2]=al.get(i).getQty();
            model.addRow(row);
        }
}
    
    //show item/data to fields:
    public void showItemToFields(int index){
        jTextSpare_ID.setText(Integer.toString(retriveData().get(index).getId()));
        jTextSpare_Name.setText(retriveData().get(index).getName());
        jTextSpare_qut.setText(Integer.toString(retriveData().get(index).getQty()));
  
        
        lbl_image.setIcon(resetImageSize(null, retriveData().get(index).getPhoto()));
        
    }
    
    
    private void CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseEntered
        changercolor(Buttonclose, new Color (232, 17, 35));
    }//GEN-LAST:event_CloseMouseEntered

    private void CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseExited
        changercolor(Buttonclose, new Color (5, 10, 46));
    }//GEN-LAST:event_CloseMouseExited

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void FullmaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullmaxMouseEntered
        changercolor(ButtonMax, new Color (25, 29, 74));
    }//GEN-LAST:event_FullmaxMouseEntered

    private void FullmaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullmaxMouseExited
        changercolor(ButtonMax, new Color (5, 10, 46));
    }//GEN-LAST:event_FullmaxMouseExited

    private void FullmaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullmaxMouseClicked
        if(this.getExtendedState()!= Spare_Parts_Details.MAXIMIZED_BOTH )
        {
            this.setExtendedState(Spare_Parts_Details.MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(Spare_Parts_Details.NORMAL);
        }
    }//GEN-LAST:event_FullmaxMouseClicked

    private void buttonhidemenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseEntered
        changercolor(linehidemenu, new Color (247,78,105));
    }//GEN-LAST:event_buttonhidemenuMouseEntered

    private void buttonhidemenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseExited
        changercolor(linehidemenu, new Color (5, 10, 46));
    }//GEN-LAST:event_buttonhidemenuMouseExited

    private void buttonhidemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseClicked
       clickmenu(hidemenu, home, 1);
       
       //create void for method hide and show panel menu
       if(a==true){
           hideshow(menu , a, buttonhidemenu);
           SwingUtilities.updateComponentTreeUI(this);
           a=false;
       }
       else{
           hideshow(menu , a ,buttonhidemenu);
           SwingUtilities.updateComponentTreeUI(this);
           a=true;
       }
       
    }//GEN-LAST:event_buttonhidemenuMouseClicked

    private void MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseEntered
        changercolor(ButtonMin, new Color (25, 29, 74));
    }//GEN-LAST:event_MinimizeMouseEntered

    private void MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseExited
        changercolor(ButtonMin, new Color (5, 10, 46));
    }//GEN-LAST:event_MinimizeMouseExited

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        
    }//GEN-LAST:event_MinimizeMouseClicked

    private void buttonhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhomeMouseEntered
       changercolor(linehome, new Color (8, 177, 150));
       changercolor(home, new Color (25,29,74));
    }//GEN-LAST:event_buttonhomeMouseEntered

    private void buttonhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhomeMouseExited
        changercolor(linehome, new Color (5, 10, 46));
        changercolor(home, new Color (5, 10, 46));
    }//GEN-LAST:event_buttonhomeMouseExited

    private void buttonhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhomeMouseClicked
        clickmenu(home, hidemenu, 1);
        
        Home E =new Home();
        E.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonhomeMouseClicked

    private void tec_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tec_detailsMouseClicked
        Technician_Details E =new Technician_Details();
        E.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tec_detailsMouseClicked

    private void tec_detailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tec_detailsMouseEntered
        changercolor(buttontec_details, new Color (145, 145, 146));
    }//GEN-LAST:event_tec_detailsMouseEntered

    private void tec_detailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tec_detailsMouseExited
        changercolor(buttontec_details, new Color (25,29,74));
    }//GEN-LAST:event_tec_detailsMouseExited

    private void stock_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_detailsMouseClicked
        Stock_Details E =new Stock_Details();
        E.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_stock_detailsMouseClicked

    private void stock_detailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_detailsMouseEntered
        changercolor(buttonstock_details, new Color (145, 145, 146));
    }//GEN-LAST:event_stock_detailsMouseEntered

    private void stock_detailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_detailsMouseExited
        changercolor(buttonstock_details, new Color (25,29,74));
    }//GEN-LAST:event_stock_detailsMouseExited

    private void stocktable_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stocktable_detailsMouseClicked
        Stock_table E =new Stock_table();
        E.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_stocktable_detailsMouseClicked

    private void stocktable_detailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stocktable_detailsMouseEntered
        changercolor(buttonstocktable_details, new Color (145, 145, 146));
    }//GEN-LAST:event_stocktable_detailsMouseEntered

    private void stocktable_detailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stocktable_detailsMouseExited
        changercolor(buttonstocktable_details, new Color (25,29,74));
    }//GEN-LAST:event_stocktable_detailsMouseExited

    private void SsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SsearchMouseClicked
       
    }//GEN-LAST:event_SsearchMouseClicked

    private void SsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SsearchMouseEntered
        changercolor(buttontsearch, new Color (110, 110, 109));
    }//GEN-LAST:event_SsearchMouseEntered

    private void SsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SsearchMouseExited
        changercolor(buttontsearch, new Color (55,55,55));
    }//GEN-LAST:event_SsearchMouseExited

    private void Bntt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bntt_addActionPerformed
    
        if((jTextSpare_ID!=null || jTextSpare_Name !=null || jTextSpare_qut !=null) && photopath != null)
        {
            try{
                Connection conn = SqlConnection();
                PreparedStatement ps = conn.prepareStatement("insert into Spare_Part" + 
                        "(Spare_Id, Spare_Name, Spare_Qty, Spare_Image) values (?,?,?,?)");
                
                ps.setInt(1,Integer.parseInt(jTextSpare_ID.getText()));
                ps.setString(2, jTextSpare_Name.getText());
                ps.setInt(3,Integer.parseInt(jTextSpare_qut.getText()));

                
                InputStream is = new FileInputStream(new File(photopath));
                ps.setBlob(4, is);
                int res = ps.executeUpdate();
                
                if(res>=1){
                    JOptionPane.showMessageDialog(null, res + " Inserted into Dtabase");
                }
                else{
                    JOptionPane.showMessageDialog(null, " Data inserted failed");
                }
                
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                
            }
            
                jTextSpare_ID.setText("");
                jTextSpare_Name.setText("");
                jTextSpare_qut.setText("");
                
        }
        else{
                    JOptionPane.showMessageDialog(null, " Data inserted failed");
                }

    }//GEN-LAST:event_Bntt_addActionPerformed

    private void Bnt_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_updateActionPerformed

        if(jTextSpare_ID != null || jTextSpare_Name != null || jTextSpare_qut !=null ){
            
            String qry=null;
            PreparedStatement ps=null;
            Connection conn = SqlConnection();
            
         if (photopath == null){
            try{
                qry="update Spare_Part set Spare_Name=? where Spare_Id=? ";
                ps=conn.prepareStatement(qry);
                
                ps.setString(1, jTextSpare_Name.getText());
                ps.setInt(2,Integer.parseInt(jTextSpare_qut.getText()));
                
                ps.setInt(3,Integer.parseInt(jTextSpare_ID.getText()));
                
                //InputStream is = new FileInputStream(new File(photopath));
                //ps.setBlob(6, is);
                
                int res = ps.executeUpdate();
            
                if(res>=1){
                    JOptionPane.showMessageDialog(null, "Spare Part Details" + "Updated Sucessfully");
                }
                else{
                    JOptionPane.showMessageDialog(null, " Spare Part Details updation failed");
                }
             
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                
            }
            
                jTextSpare_ID.setText("");
                jTextSpare_Name.setText("");
                jTextSpare_qut.setText("");
                
         }
         
            else{
               
              try{
                  
                 InputStream is=new FileInputStream(new File(photopath));
                  
                qry="update Spare_Part set Spare_Name=?, Spare_Qty=?, Spare_Image=? where Spare_Id=? ";
                ps=conn.prepareStatement(qry);
                
                ps.setString(1, jTextSpare_Name.getText());
                
                ps.setInt(2,Integer.parseInt(jTextSpare_qut.getText()));
                
                ps.setBlob(3, is);
                
                ps.setInt(4,Integer.parseInt(jTextSpare_ID.getText()));
                
                
                int res = ps.executeUpdate();
            
                if(res>=1){
                    JOptionPane.showMessageDialog(null, "Spare Part Details" + "Updated Sucessfully");
                }
                else{
                    JOptionPane.showMessageDialog(null, " Spare Part Details updation failed");
                }
             
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                
            }
            
                jTextSpare_ID.setText("");
                jTextSpare_Name.setText("");
                jTextSpare_qut.setText("");
             
                }
         
       }else{
            JOptionPane.showMessageDialog(null, " Spare Part Details updation failed");
        }
 
    }//GEN-LAST:event_Bnt_updateActionPerformed

    private void Bnt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_deleteActionPerformed
        
        if(jTextSpare_ID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter Spare Part id:");
            
        }else{
            try{
                String qry= "delete from Spare_Part where Spare_Id=?";
                Connection conn=SqlConnection();
                PreparedStatement ps=conn.prepareStatement(qry);
                ps.setInt(1, Integer.parseInt(jTextSpare_ID.getText().toString()));
                
                int res=ps.executeUpdate();
                if(res>=1){
                   JOptionPane.showMessageDialog(null, "Deleted Sucessfully");
                }else{
                    JOptionPane.showMessageDialog(null, "Deletion Failed");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            
                jTextSpare_ID.setText("");
                jTextSpare_Name.setText("");
                jTextSpare_qut.setText("");
        }
        
        
    }//GEN-LAST:event_Bnt_deleteActionPerformed

    private void butt_Choose_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_Choose_imageActionPerformed
        
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")) );
        
        //filter the files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg", "png", "gif  ");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        
        //if the user click on save in JFIleChooser
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lbl_image.setIcon(resetImageSize(path,null));
            this.photopath=path;
        }
        else{
            System.out.println("No File Selected");
        }
        
    
    }//GEN-LAST:event_butt_Choose_imageActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jTable1_SpareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_SpareMouseClicked
        int ind=jTable1_Spare.getSelectedRow();
        showItemToFields(ind);
    }//GEN-LAST:event_jTable1_SpareMouseClicked

    private void jText_SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_SearchKeyPressed
        
        ArrayList<SparePartDeatilsBean> al = null;
        al= new ArrayList<SparePartDeatilsBean>();
        String val=jText_Search.getText().toString();
        
        try{
            Connection conn=SqlConnection();
            
            String qry="select * from Spare_Part where Spare_Name  like '%"+val+"%'";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(qry);
            SparePartDeatilsBean Spare;
            while(rs.next()){
                Spare= new SparePartDeatilsBean(rs.getInt(1), rs.getString(2),rs.getInt(3),rs.getBytes(4));
                al.add(Spare);
            }
            
            DefaultTableModel model=(DefaultTableModel)jTable1_Spare.getModel();
            model.setRowCount(0);
        
            Object[] row = new Object[3];
            for(int i=0; i<al.size(); i++){
                row[0]=al.get(i).getId();
                row[1]=al.get(i).getName();
                row[2]=al.get(i).getQty();
                model.addRow(row);
        }
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jText_SearchKeyPressed

    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Spare_Parts_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Spare_Parts_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Spare_Parts_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Spare_Parts_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Spare_Parts_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bnt_delete;
    private javax.swing.JButton Bnt_update;
    private javax.swing.JButton Bntt_add;
    private javax.swing.JPanel ButtonMax;
    private javax.swing.JPanel ButtonMin;
    private javax.swing.JPanel Buttonclose;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Fullmax;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Heading;
    private javax.swing.JPanel Iconminmaxclose;
    private javax.swing.JPanel MenuIcon;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Ssearch;
    private javax.swing.JButton butt_Choose_image;
    private javax.swing.JLabel buttonhidemenu;
    private javax.swing.JLabel buttonhome;
    private javax.swing.JPanel buttonstock_details;
    private javax.swing.JPanel buttonstocktable_details;
    private javax.swing.JPanel buttontec_details;
    private javax.swing.JPanel buttontsearch;
    private javax.swing.JPanel dashbordview;
    private javax.swing.JPanel hidemenu;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1_Spare;
    private javax.swing.JTextField jTextSpare_ID;
    private javax.swing.JTextField jTextSpare_Name;
    private javax.swing.JTextField jTextSpare_qut;
    private javax.swing.JTextField jText_Search;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JPanel linehidemenu;
    private javax.swing.JPanel linehome;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuhide;
    private javax.swing.JLabel stock_details;
    private javax.swing.JLabel stocktable_details;
    private javax.swing.JLabel tec_details;
    // End of variables declaration//GEN-END:variables

}
    
