/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DIL-SOFT 02
 */
public class Technician_Details extends javax.swing.JFrame {

    
    
    boolean a = true;
    
    public Technician_Details() {
        initComponents();
        dashbordview.setBackground(new Color(0,0,0,200));
        fillTable();
        SqlConnection();
  
    }
    
  
    
    
    //Database connection
    public Connection SqlConnection(){
        
        Connection conn =  null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Stock_System","root","");
            //JOptionPane.showMessageDialog(null, "Database connected Sucessfully");
            return conn;
            
        } catch (Exception e) {
                       JOptionPane.showMessageDialog(null, "Mysql connected fail");
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        Iconminmaxclose = new javax.swing.JPanel();
        Buttonclose = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        ButtonMax = new javax.swing.JPanel();
        Fullmax = new javax.swing.JLabel();
        ButtonMin = new javax.swing.JPanel();
        Minimize = new javax.swing.JLabel();
        Heading = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        MenuIcon = new javax.swing.JPanel();
        linehome = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        buttonhome = new javax.swing.JLabel();
        linehidemenu = new javax.swing.JPanel();
        hidemenu = new javax.swing.JPanel();
        buttonhidemenu = new javax.swing.JLabel();
        menuhide = new javax.swing.JPanel();
        buttonsparepart_details = new javax.swing.JPanel();
        sparepart_details = new javax.swing.JLabel();
        buttonstock_details = new javax.swing.JPanel();
        stock_details = new javax.swing.JLabel();
        buttonstocktable_details = new javax.swing.JPanel();
        stocktable_details = new javax.swing.JLabel();
        dashbordview = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTexttech_position = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTexttech_ID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTexttech_Name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_image = new javax.swing.JLabel();
        Bnt_Choose_image = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Bnt_delete = new javax.swing.JButton();
        Bnt_add = new javax.swing.JButton();
        Bnt_update = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTexttech_Address = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jTexttech_Pno = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        buttontsearch = new javax.swing.JPanel();
        tsearch = new javax.swing.JLabel();
        jText_Search = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        Backgroundimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(5, 10, 46));
        Header.setPreferredSize(new java.awt.Dimension(1360, 50));
        Header.setLayout(new java.awt.BorderLayout());

        Iconminmaxclose.setBackground(new java.awt.Color(5, 10, 46));
        Iconminmaxclose.setPreferredSize(new java.awt.Dimension(150, 50));
        Iconminmaxclose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buttonclose.setBackground(new java.awt.Color(5, 10, 46));
        Buttonclose.setLayout(new java.awt.BorderLayout());

        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_25px.png"))); // NOI18N
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseMouseExited(evt);
            }
        });
        Buttonclose.add(Close, java.awt.BorderLayout.CENTER);

        Iconminmaxclose.add(Buttonclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        ButtonMax.setBackground(new java.awt.Color(5, 10, 46));
        ButtonMax.setPreferredSize(new java.awt.Dimension(50, 50));
        ButtonMax.setLayout(new java.awt.BorderLayout());

        Fullmax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fullmax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/full_screen_25px.png"))); // NOI18N
        Fullmax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FullmaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FullmaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FullmaxMouseExited(evt);
            }
        });
        ButtonMax.add(Fullmax, java.awt.BorderLayout.CENTER);

        Iconminmaxclose.add(ButtonMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        ButtonMin.setBackground(new java.awt.Color(5, 10, 46));
        ButtonMin.setLayout(new java.awt.BorderLayout());

        Minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize_window_25px.png"))); // NOI18N
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeMouseExited(evt);
            }
        });
        ButtonMin.add(Minimize, java.awt.BorderLayout.CENTER);

        Iconminmaxclose.add(ButtonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        Header.add(Iconminmaxclose, java.awt.BorderLayout.LINE_END);

        Heading.setBackground(new java.awt.Color(5, 10, 46));
        Heading.setPreferredSize(new java.awt.Dimension(350, 50));
        Heading.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Maiandra GD", 1, 27)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/workers_45px.png"))); // NOI18N
        jLabel9.setText("Technician Details");
        jLabel9.setToolTipText("");
        Heading.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 290, 40));

        Header.add(Heading, java.awt.BorderLayout.LINE_START);

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 50));

        menu.setPreferredSize(new java.awt.Dimension(276, 680));
        menu.setLayout(new java.awt.BorderLayout());

        MenuIcon.setBackground(new java.awt.Color(5, 10, 46));
        MenuIcon.setPreferredSize(new java.awt.Dimension(65, 630));
        MenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linehome.setBackground(new java.awt.Color(5, 10, 46));
        linehome.setPreferredSize(new java.awt.Dimension(65, 5));

        javax.swing.GroupLayout linehomeLayout = new javax.swing.GroupLayout(linehome);
        linehome.setLayout(linehomeLayout);
        linehomeLayout.setHorizontalGroup(
            linehomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        linehomeLayout.setVerticalGroup(
            linehomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(linehome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 65, 5));

        home.setBackground(new java.awt.Color(5, 10, 46));
        home.setPreferredSize(new java.awt.Dimension(65, 65));
        home.setLayout(new java.awt.BorderLayout());

        buttonhome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_30px.png"))); // NOI18N
        buttonhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhomeMouseExited(evt);
            }
        });
        home.add(buttonhome, java.awt.BorderLayout.CENTER);

        MenuIcon.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 65, 65));

        linehidemenu.setBackground(new java.awt.Color(5, 10, 46));
        linehidemenu.setPreferredSize(new java.awt.Dimension(65, 5));

        javax.swing.GroupLayout linehidemenuLayout = new javax.swing.GroupLayout(linehidemenu);
        linehidemenu.setLayout(linehidemenuLayout);
        linehidemenuLayout.setHorizontalGroup(
            linehidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        linehidemenuLayout.setVerticalGroup(
            linehidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(linehidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 65, 5));

        hidemenu.setBackground(new java.awt.Color(5, 10, 46));
        hidemenu.setPreferredSize(new java.awt.Dimension(65, 65));
        hidemenu.setLayout(new java.awt.BorderLayout());

        buttonhidemenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonhidemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_30px.png"))); // NOI18N
        buttonhidemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseExited(evt);
            }
        });
        hidemenu.add(buttonhidemenu, java.awt.BorderLayout.CENTER);

        MenuIcon.add(hidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 65, 65));

        menu.add(MenuIcon, java.awt.BorderLayout.LINE_START);

        menuhide.setBackground(new java.awt.Color(25, 29, 74));
        menuhide.setPreferredSize(new java.awt.Dimension(211, 650));

        buttonsparepart_details.setBackground(new java.awt.Color(25, 29, 74));
        buttonsparepart_details.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 10, 46), 1, true));

        sparepart_details.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        sparepart_details.setForeground(new java.awt.Color(255, 255, 255));
        sparepart_details.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sparepart_details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/maintenance_45px.png"))); // NOI18N
        sparepart_details.setText("Sapre Part Details");
        sparepart_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sparepart_detailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sparepart_detailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sparepart_detailsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttonsparepart_detailsLayout = new javax.swing.GroupLayout(buttonsparepart_details);
        buttonsparepart_details.setLayout(buttonsparepart_detailsLayout);
        buttonsparepart_detailsLayout.setHorizontalGroup(
            buttonsparepart_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sparepart_details, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        buttonsparepart_detailsLayout.setVerticalGroup(
            buttonsparepart_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sparepart_details)
        );

        buttonstock_details.setBackground(new java.awt.Color(25, 29, 74));
        buttonstock_details.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 10, 46), 1, true));

        stock_details.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        stock_details.setForeground(new java.awt.Color(255, 255, 255));
        stock_details.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stock_details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/warehouse_45px.png"))); // NOI18N
        stock_details.setText("Stock Details");
        stock_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stock_detailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stock_detailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stock_detailsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttonstock_detailsLayout = new javax.swing.GroupLayout(buttonstock_details);
        buttonstock_details.setLayout(buttonstock_detailsLayout);
        buttonstock_detailsLayout.setHorizontalGroup(
            buttonstock_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonstock_detailsLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(stock_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonstock_detailsLayout.setVerticalGroup(
            buttonstock_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonstock_detailsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(stock_details))
        );

        buttonstocktable_details.setBackground(new java.awt.Color(25, 29, 74));
        buttonstocktable_details.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 10, 46), 1, true));

        stocktable_details.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        stocktable_details.setForeground(new java.awt.Color(255, 255, 255));
        stocktable_details.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stocktable_details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/view_45px.png"))); // NOI18N
        stocktable_details.setText("Stock Table Details");
        stocktable_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stocktable_detailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stocktable_detailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stocktable_detailsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttonstocktable_detailsLayout = new javax.swing.GroupLayout(buttonstocktable_details);
        buttonstocktable_details.setLayout(buttonstocktable_detailsLayout);
        buttonstocktable_detailsLayout.setHorizontalGroup(
            buttonstocktable_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonstocktable_detailsLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(stocktable_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        buttonstocktable_detailsLayout.setVerticalGroup(
            buttonstocktable_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonstocktable_detailsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(stocktable_details))
        );

        javax.swing.GroupLayout menuhideLayout = new javax.swing.GroupLayout(menuhide);
        menuhide.setLayout(menuhideLayout);
        menuhideLayout.setHorizontalGroup(
            menuhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonsparepart_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonstock_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonstocktable_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuhideLayout.setVerticalGroup(
            menuhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuhideLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(buttonsparepart_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(buttonstock_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(buttonstocktable_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        menu.add(menuhide, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 276, 670));

        dashbordview.setBackground(new java.awt.Color(0, 0, 0));
        dashbordview.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dashbordview.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Image:");
        dashbordview.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 130, 30));

        jTexttech_position.setBackground(new java.awt.Color(55, 55, 55));
        jTexttech_position.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTexttech_position.setForeground(new java.awt.Color(255, 255, 255));
        jTexttech_position.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTexttech_position.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTexttech_position.setCaretColor(new java.awt.Color(55, 55, 55));
        jTexttech_position.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTexttech_position.setSelectionColor(new java.awt.Color(55, 55, 55));
        dashbordview.add(jTexttech_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 260, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Technician ID:");
        dashbordview.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 100, 30));

        jTexttech_ID.setBackground(new java.awt.Color(55, 55, 55));
        jTexttech_ID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTexttech_ID.setForeground(new java.awt.Color(255, 255, 255));
        jTexttech_ID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTexttech_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTexttech_ID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTexttech_ID.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTexttech_ID.setSelectionColor(new java.awt.Color(55, 55, 55));
        dashbordview.add(jTexttech_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 260, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Technician Name:");
        dashbordview.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 130, 30));

        jTexttech_Name.setBackground(new java.awt.Color(55, 55, 55));
        jTexttech_Name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTexttech_Name.setForeground(new java.awt.Color(255, 255, 255));
        jTexttech_Name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTexttech_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTexttech_Name.setCaretColor(new java.awt.Color(55, 55, 55));
        jTexttech_Name.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTexttech_Name.setSelectionColor(new java.awt.Color(55, 55, 55));
        dashbordview.add(jTexttech_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 260, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Position:");
        dashbordview.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 70, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address:");
        dashbordview.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 80, 30));

        lbl_image.setBackground(new java.awt.Color(55, 55, 55));
        lbl_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_image.setOpaque(true);
        dashbordview.add(lbl_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 260, 100));

        Bnt_Choose_image.setBackground(new java.awt.Color(102, 102, 102));
        Bnt_Choose_image.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Bnt_Choose_image.setForeground(new java.awt.Color(255, 255, 255));
        Bnt_Choose_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Image_file_button.png"))); // NOI18N
        Bnt_Choose_image.setText("Choose Image");
        Bnt_Choose_image.setBorder(null);
        Bnt_Choose_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_Choose_imageActionPerformed(evt);
            }
        });
        dashbordview.add(Bnt_Choose_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 160, 30));
        dashbordview.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 52, 260, 10));
        dashbordview.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 124, 260, -1));
        dashbordview.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 202, 260, 10));

        Bnt_delete.setBackground(new java.awt.Color(102, 102, 102));
        Bnt_delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Bnt_delete.setForeground(new java.awt.Color(255, 255, 255));
        Bnt_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button_delete-cute.png"))); // NOI18N
        Bnt_delete.setText("Delete");
        Bnt_delete.setBorder(null);
        Bnt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_deleteActionPerformed(evt);
            }
        });
        dashbordview.add(Bnt_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 610, 130, 40));

        Bnt_add.setBackground(new java.awt.Color(102, 102, 102));
        Bnt_add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Bnt_add.setForeground(new java.awt.Color(255, 255, 255));
        Bnt_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button_add-cute.png"))); // NOI18N
        Bnt_add.setText("Add");
        Bnt_add.setBorder(null);
        Bnt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_addActionPerformed(evt);
            }
        });
        dashbordview.add(Bnt_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, 130, 40));

        Bnt_update.setBackground(new java.awt.Color(102, 102, 102));
        Bnt_update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Bnt_update.setForeground(new java.awt.Color(255, 255, 255));
        Bnt_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button_update-cute.png"))); // NOI18N
        Bnt_update.setText("Update");
        Bnt_update.setBorder(null);
        Bnt_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_updateActionPerformed(evt);
            }
        });
        dashbordview.add(Bnt_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 610, 130, 40));

        jTexttech_Address.setBackground(new java.awt.Color(55, 55, 55));
        jTexttech_Address.setColumns(20);
        jTexttech_Address.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTexttech_Address.setForeground(new java.awt.Color(255, 255, 255));
        jTexttech_Address.setRows(5);
        jTexttech_Address.setBorder(null);
        jScrollPane2.setViewportView(jTexttech_Address);

        dashbordview.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 260, 80));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contatct NO:");
        dashbordview.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 100, 30));

        jTexttech_Pno.setBackground(new java.awt.Color(55, 55, 55));
        jTexttech_Pno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTexttech_Pno.setForeground(new java.awt.Color(255, 255, 255));
        jTexttech_Pno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTexttech_Pno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTexttech_Pno.setCaretColor(new java.awt.Color(55, 55, 55));
        jTexttech_Pno.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTexttech_Pno.setSelectionColor(new java.awt.Color(55, 55, 55));
        dashbordview.add(jTexttech_Pno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 260, 30));
        dashbordview.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 324, 260, 20));
        dashbordview.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 260, 20));

        buttontsearch.setBackground(new java.awt.Color(55, 55, 55));
        buttontsearch.setPreferredSize(new java.awt.Dimension(40, 40));
        buttontsearch.setLayout(new java.awt.BorderLayout());

        tsearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_20px.png"))); // NOI18N
        tsearch.setPreferredSize(new java.awt.Dimension(35, 30));
        tsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tsearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tsearchMouseExited(evt);
            }
        });
        buttontsearch.add(tsearch, java.awt.BorderLayout.LINE_START);

        jText_Search.setBackground(new java.awt.Color(55, 55, 55));
        jText_Search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jText_Search.setForeground(new java.awt.Color(255, 255, 255));
        jText_Search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jText_Search.setPreferredSize(new java.awt.Dimension(265, 30));
        jText_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jText_SearchMousePressed(evt);
            }
        });
        jText_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jText_SearchKeyReleased(evt);
            }
        });
        buttontsearch.add(jText_Search, java.awt.BorderLayout.CENTER);

        dashbordview.add(buttontsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 300, 30));

        jScrollPane3.setBackground(new java.awt.Color(55, 55, 55));
        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(55, 55, 55));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 55, 55)));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Technician ID", "Technician Name", "Contact NO", "Requirment", "Position"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(55, 55, 55));
        jTable1.setRowHeight(26);
        jTable1.setRowMargin(8);
        jTable1.setSelectionBackground(new java.awt.Color(110, 110, 109));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        dashbordview.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 530, 310));
        dashbordview.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 260, 20));
        dashbordview.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 432, 300, 10));

        getContentPane().add(dashbordview, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 1040, 670));

        Backgroundimage.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIL-SOFT 02\\Documents\\NetBeansProjects\\Spare Part\\src\\Images\\Image 2.jpg")); // NOI18N
        Backgroundimage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Backgroundimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 1030, 670));

        setSize(new java.awt.Dimension(1311, 721));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //change lable colors
    public void changercolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    public void clickmenu(JPanel h1, JPanel h2, int numberbool){
       if(numberbool == 1){
           h1.setBackground(new Color(25, 29, 74));
           h2.setBackground(new Color(5, 10, 46));
       } 
       else{
           h1.setBackground(new Color(5, 10, 46));
           h2.setBackground(new Color(25, 29, 74));
       }
    }
    
    //method for change image
    public void changeImage (JLabel button, String resourcheimg){
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
        button.setIcon(aimg);
    } 
    
    
    //menu
    public void hideshow(JPanel menushowhide, boolean dashboard, JLabel button){
        if(dashboard == true){
            menushowhide.setPreferredSize(new Dimension(65, menushowhide.getHeight()));
            changeImage(button,"/Images/menu_30px.png");
        }
        else{
            menushowhide.setPreferredSize(new Dimension(276, menushowhide.getHeight()));
            changeImage(button,"/Images/back_30px.png");
        }
    }
    
     String photopath = "";
        //Resize Image
    public ImageIcon resetImageSize(String photopath, byte[] photo)
    {
        ImageIcon myPhoto = null;
        
        if(photopath != null){
            myPhoto = new ImageIcon(photopath);
        }
        else{
            myPhoto = new ImageIcon(photo);
        }
        
        Image img = myPhoto .getImage();
        Image img1 = img.getScaledInstance(lbl_image.getHeight(), lbl_image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ph = new ImageIcon(img1);
        return ph;
    }
    
    
    //Show or add the data to the table
    public ArrayList<TechnicianBean> retriveData(){
        ArrayList<TechnicianBean> al=null;
        al=new ArrayList<TechnicianBean>();
        
        try{
            Connection conn=SqlConnection();
            String qry="Select * from Technician";
            Statement st=conn.createStatement();
            ResultSet rs= st.executeQuery(qry);
            TechnicianBean Tech;
            while(rs.next()){
                Tech= new TechnicianBean(rs.getInt(1), rs.getString(2), rs.getInt(3), rs.getString(4),
                rs.getString(5),rs.getBytes(6));
                al.add(Tech);
            }
        }catch(Exception e){
            System.out.println("Error in retriveData method:"+e);
            
        }
       return al; 
    }
    
    public void fillTable(){
        ArrayList<TechnicianBean> al = retriveData();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        
        Object[] row = new Object[5];
        for(int i=0; i<al.size(); i++){
            row[0]=al.get(i).getId();
            row[1]=al.get(i).getName();
            row[2]=al.get(i).getPno();
            row[3]=al.get(i).getAddress();
            row[4]=al.get(i).getPosition();
            model.addRow(row);
        }
}
    
    //show item/data to fields:
    public void showItemToFields(int index){
        jTexttech_ID.setText(Integer.toString(retriveData().get(index).getId()));
        jTexttech_Name.setText(retriveData().get(index).getName());
        jTexttech_Pno.setText(Integer.toString(retriveData().get(index).getPno()));
        jTexttech_Address.setText(retriveData().get(index).getAddress());
        jTexttech_position.setText(retriveData().get(index).getPosition());
        
        lbl_image.setIcon(resetImageSize(null, retriveData().get(index).getPhoto()));
        
    }
    
    
    private void CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseEntered
        changercolor(Buttonclose, new Color (232, 17, 35));
    }//GEN-LAST:event_CloseMouseEntered

    private void CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseExited
        changercolor(Buttonclose, new Color (5, 10, 46));
    }//GEN-LAST:event_CloseMouseExited

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void FullmaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullmaxMouseEntered
        changercolor(ButtonMax, new Color (51, 84, 158));
    }//GEN-LAST:event_FullmaxMouseEntered

    private void FullmaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullmaxMouseExited
        changercolor(ButtonMax, new Color (5, 10, 46));
    }//GEN-LAST:event_FullmaxMouseExited

    private void FullmaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullmaxMouseClicked
        if(this.getExtendedState()!= Technician_Details.MAXIMIZED_BOTH )
        {
            this.setExtendedState(Technician_Details.MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(Technician_Details.NORMAL);
        }
    }//GEN-LAST:event_FullmaxMouseClicked

    private void buttonhidemenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseEntered
        changercolor(linehidemenu, new Color (247,78,105));
    }//GEN-LAST:event_buttonhidemenuMouseEntered

    private void buttonhidemenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseExited
        changercolor(linehidemenu, new Color (5, 10, 46));
    }//GEN-LAST:event_buttonhidemenuMouseExited

    private void buttonhidemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseClicked
       clickmenu(hidemenu, home, 1);
       
       //create void for method hide and show panel menu
       if(a==true){
           hideshow(menu , a, buttonhidemenu);
           SwingUtilities.updateComponentTreeUI(this);
           a=false;
       }
       else{
           hideshow(menu , a, buttonhidemenu);
           SwingUtilities.updateComponentTreeUI(this);
           a=true;
       }
       
    }//GEN-LAST:event_buttonhidemenuMouseClicked

    private void MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseEntered
        changercolor(ButtonMin, new Color (25, 29, 74));
    }//GEN-LAST:event_MinimizeMouseEntered

    private void MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseExited
        changercolor(ButtonMin, new Color (5, 10, 46));
    }//GEN-LAST:event_MinimizeMouseExited

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        
    }//GEN-LAST:event_MinimizeMouseClicked

    private void buttonhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhomeMouseEntered
       changercolor(linehome, new Color (8, 177, 150));
       changercolor(home, new Color (25,29,74));
    }//GEN-LAST:event_buttonhomeMouseEntered

    private void buttonhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhomeMouseExited
        changercolor(linehome, new Color (5, 10, 46));
        changercolor(home, new Color (5, 10, 46));
    }//GEN-LAST:event_buttonhomeMouseExited

    private void buttonhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhomeMouseClicked
        clickmenu(home, hidemenu, 1);
        
        Home E =new Home();
        E.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonhomeMouseClicked

    private void tsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsearchMouseClicked
     
    }//GEN-LAST:event_tsearchMouseClicked

    private void tsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsearchMouseEntered
        changercolor(buttontsearch, new Color (110, 110, 109));
    }//GEN-LAST:event_tsearchMouseEntered

    private void tsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsearchMouseExited
        changercolor(buttontsearch, new Color (55,55,55));
    }//GEN-LAST:event_tsearchMouseExited

    private void Bnt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_addActionPerformed
      
        if((jTexttech_ID !=null || jTexttech_Name !=null ||
                jTexttech_Pno !=null || jTexttech_Address !=null ||
                jTexttech_position !=null) && photopath != null)
        {
            try{
                Connection conn = SqlConnection();
               
                PreparedStatement ps = conn.prepareStatement("insert into Technician" + 
                        "(Tech_id, Tech_Name,Tech_PNO,Tech_Address,Tech_Position, Tech_Image) values (?,?,?,?,?,?)");
                
                ps.setInt(1,Integer.parseInt(jTexttech_ID.getText()));
                ps.setString(2, jTexttech_Name.getText());
                ps.setInt(3,Integer.parseInt(jTexttech_Pno.getText()));
                ps.setString(4, jTexttech_Address.getText());
                ps.setString(5, jTexttech_position.getText());
                
                InputStream is = new FileInputStream(new File(photopath));
                ps.setBlob(6, is);
                int res = ps.executeUpdate();
                
                if(res>=1){
                    JOptionPane.showMessageDialog(null, res + " Inserted into Dtabase");
                }
                else{
                    JOptionPane.showMessageDialog(null, " Data inserted failed");
                }
                
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                
            }
            
                jTexttech_ID.setText("");
                jTexttech_Name.setText("");
                jTexttech_Pno.setText("");
                jTexttech_Address.setText("");
                jTexttech_position.setText("");
                
        }
        else{
                    JOptionPane.showMessageDialog(null, " Data inserted failed");
                }
    }//GEN-LAST:event_Bnt_addActionPerformed

    private void Bnt_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_updateActionPerformed
       
        if(jTexttech_ID != null || jTexttech_Name != null || jTexttech_Pno != null || jTexttech_Address != null ||
                jTexttech_position != null){
            
            String qry=null;
            PreparedStatement ps=null;
            Connection conn = SqlConnection();
            
         if (photopath == null){
            try{
                qry="update  Technician set Tech_Name=?, Tech_PNO=?, Tech_Address=?,Tech_Position=? where Tech_Id=? ";
                ps=conn.prepareStatement(qry);
                
                ps.setString(1, jTexttech_Name.getText());
                ps.setInt(2,Integer.parseInt(jTexttech_Pno.getText()));
                ps.setString(3, jTexttech_Address.getText());
                ps.setString(4, jTexttech_position.getText());
                
                ps.setInt(5,Integer.parseInt(jTexttech_ID.getText()));
                //InputStream is = new FileInputStream(new File(photopath));
                //ps.setBlob(6, is);
                
                int res = ps.executeUpdate();
            
                if(res>=1){
                    JOptionPane.showMessageDialog(null, "Technician" + "Updated Sucessfully");
                }
                else{
                    JOptionPane.showMessageDialog(null, " Technician Details updation failed");
                }
             
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                
            }
            
                jTexttech_ID.setText("");
                jTexttech_Name.setText("");
                jTexttech_Pno.setText("");
                jTexttech_Address.setText("");
                jTexttech_position.setText("");
                
         }
         
            else{
               
              try{
                  
                InputStream is=new FileInputStream(new File(photopath));
                  
                qry="update Technician set Tech_Name=?, Tech_PNO=?, Tech_Address=?,Tech_Position=?,Tech_Image=? where Tech_Id=? ";
                ps=conn.prepareStatement(qry);
                
                ps.setString(1, jTexttech_Name.getText());
                ps.setInt(2,Integer.parseInt(jTexttech_Pno.getText()));
                ps.setString(3, jTexttech_Address.getText());
                ps.setString(4, jTexttech_position.getText());
                
                ps.setBlob(5, is);
                
                ps.setInt(6,Integer.parseInt(jTexttech_ID.getText()));
                
                
                int res = ps.executeUpdate();
            
                if(res>=1){
                    JOptionPane.showMessageDialog(null, "Technician" + "Updated Sucessfully");
                }
                else{
                    JOptionPane.showMessageDialog(null, " Technician Details updation failed");
                }
             
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                
            }
            
                jTexttech_ID.setText("");
                jTexttech_Name.setText("");
                jTexttech_Pno.setText("");
                jTexttech_Address.setText("");
                jTexttech_position.setText("");
             
                }
         
       }else{
            JOptionPane.showMessageDialog(null, " Technician Details updation failed");
        }
    }//GEN-LAST:event_Bnt_updateActionPerformed

    private void Bnt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_deleteActionPerformed
    
        if(jTexttech_ID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter technician id:");
            
        }else{
            try{
                String qry= "delete from Technician where Tech_Id=?";
                Connection conn=SqlConnection();
                PreparedStatement ps=conn.prepareStatement(qry);
                ps.setInt(1, Integer.parseInt(jTexttech_ID.getText().toString()));
                
                int res=ps.executeUpdate();
                if(res>=1){
                   JOptionPane.showMessageDialog(null, "Deleted Sucessfully");
                }else{
                    JOptionPane.showMessageDialog(null, "Deletion Failed");
                }
                
                jTexttech_ID.setText("");
                jTexttech_Name.setText("");
                jTexttech_Pno.setText("");
                jTexttech_Address.setText("");
                jTexttech_position.setText("");
            }
           
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
 
    }//GEN-LAST:event_Bnt_deleteActionPerformed

    private void Bnt_Choose_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_Choose_imageActionPerformed
      
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")) );
        
        //filter the files
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("*.images", "jpg", "png", "gif");
        chooser.addChoosableFileFilter(fnef);
        int ans = chooser.showSaveDialog(null);
        
        //if the user click on save in JFIleChooser
        if(ans == JFileChooser.APPROVE_OPTION)
        {
            File selectedPhoto = chooser.getSelectedFile();
            String path = selectedPhoto.getAbsolutePath();
            lbl_image.setIcon(resetImageSize(path,null));
            this.photopath=path;
        }
        else{
            System.out.println("No File Selected");
        }
        
    }//GEN-LAST:event_Bnt_Choose_imageActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int ind=jTable1.getSelectedRow();
        showItemToFields(ind);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jText_SearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jText_SearchMousePressed
      
    }//GEN-LAST:event_jText_SearchMousePressed

    private void jText_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_SearchKeyReleased
        
        ArrayList<TechnicianBean> al = null;
        al= new ArrayList<TechnicianBean>();
        String val=jText_Search.getText().toString();
        
        try{
            Connection conn=SqlConnection();
            
            String qry="select * from Technician where Tech_Name like '%"+val+"%'";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(qry);
            TechnicianBean Tech;
            while(rs.next()){
                Tech= new TechnicianBean(rs.getInt(1), rs.getString(2), rs.getInt(3), rs.getString(4),
                rs.getString(5),rs.getBytes(6));
                al.add(Tech);
            }
            
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
        
            Object[] row = new Object[5];
            for(int i=0; i<al.size(); i++){
                row[0]=al.get(i).getId();
                row[1]=al.get(i).getName();
                row[2]=al.get(i).getPno();
                row[3]=al.get(i).getAddress();
                row[4]=al.get(i).getPosition();
                model.addRow(row);
        }
            
        } catch (Exception e) {
            System.out.println(e);
        }
 
                
    }//GEN-LAST:event_jText_SearchKeyReleased

    private void stocktable_detailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stocktable_detailsMouseExited
        changercolor(buttonstocktable_details, new Color (25,29,74));
    }//GEN-LAST:event_stocktable_detailsMouseExited

    private void stocktable_detailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stocktable_detailsMouseEntered
        changercolor(buttonstocktable_details, new Color (145, 145, 146));
    }//GEN-LAST:event_stocktable_detailsMouseEntered

    private void stocktable_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stocktable_detailsMouseClicked
        Stock_table E =new Stock_table();
        E.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_stocktable_detailsMouseClicked

    private void stock_detailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_detailsMouseExited
        changercolor(buttonstock_details, new Color (25,29,74));
    }//GEN-LAST:event_stock_detailsMouseExited

    private void stock_detailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_detailsMouseEntered
        changercolor(buttonstock_details, new Color (145, 145, 146));
    }//GEN-LAST:event_stock_detailsMouseEntered

    private void stock_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_detailsMouseClicked
        Stock_Details E =new Stock_Details();
        E.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_stock_detailsMouseClicked

    private void sparepart_detailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sparepart_detailsMouseExited
        changercolor(buttonsparepart_details, new Color (25,29,74));
    }//GEN-LAST:event_sparepart_detailsMouseExited

    private void sparepart_detailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sparepart_detailsMouseEntered
        changercolor(buttonsparepart_details, new Color (145, 145, 146));
    }//GEN-LAST:event_sparepart_detailsMouseEntered

    private void sparepart_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sparepart_detailsMouseClicked
        Spare_Parts_Details E =new Spare_Parts_Details();
        E.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sparepart_detailsMouseClicked

    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Technician_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Technician_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Technician_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Technician_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Technician_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroundimage;
    private javax.swing.JButton Bnt_Choose_image;
    private javax.swing.JButton Bnt_add;
    private javax.swing.JButton Bnt_delete;
    private javax.swing.JButton Bnt_update;
    private javax.swing.JPanel ButtonMax;
    private javax.swing.JPanel ButtonMin;
    private javax.swing.JPanel Buttonclose;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Fullmax;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Heading;
    private javax.swing.JPanel Iconminmaxclose;
    private javax.swing.JPanel MenuIcon;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel buttonhidemenu;
    private javax.swing.JLabel buttonhome;
    private javax.swing.JPanel buttonsparepart_details;
    private javax.swing.JPanel buttonstock_details;
    private javax.swing.JPanel buttonstocktable_details;
    private javax.swing.JPanel buttontsearch;
    private javax.swing.JPanel dashbordview;
    private javax.swing.JPanel hidemenu;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jText_Search;
    private javax.swing.JTextArea jTexttech_Address;
    private javax.swing.JTextField jTexttech_ID;
    private javax.swing.JTextField jTexttech_Name;
    private javax.swing.JTextField jTexttech_Pno;
    private javax.swing.JTextField jTexttech_position;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JPanel linehidemenu;
    private javax.swing.JPanel linehome;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuhide;
    private javax.swing.JLabel sparepart_details;
    private javax.swing.JLabel stock_details;
    private javax.swing.JLabel stocktable_details;
    private javax.swing.JLabel tsearch;
    // End of variables declaration//GEN-END:variables

}
    
