/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Interface.Technician_Details;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DIL-SOFT 02
 */
public class User_RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form User_Login
     */
    public User_RegisterForm() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
        //Database connection
    public Connection SqlConnection(){
        
        Connection conn =  null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Stock_System","root","");
            return conn;
            
        } catch (Exception e) {
                       JOptionPane.showMessageDialog(null, "Mysql connected fail");
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonclose = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        buttonback = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextU_UName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jTextU_Password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        butto_signup = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextU_Name = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jTextU_CPassword = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jTextU_Email = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jTextU_PNO = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(5, 10, 46));
        jPanel1.setPreferredSize(new java.awt.Dimension(394, 70));

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 58)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User");

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RegisterForm");

        buttonclose.setBackground(new java.awt.Color(5, 10, 46));
        buttonclose.setMinimumSize(new java.awt.Dimension(25, 25));
        buttonclose.setLayout(new java.awt.BorderLayout());

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_25px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        buttonclose.add(close, java.awt.BorderLayout.CENTER);

        buttonback.setBackground(new java.awt.Color(5, 10, 46));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_50px.png"))); // NOI18N
        back.setPreferredSize(new java.awt.Dimension(35, 35));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttonbackLayout = new javax.swing.GroupLayout(buttonback);
        buttonback.setLayout(buttonbackLayout);
        buttonbackLayout.setHorizontalGroup(
            buttonbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );
        buttonbackLayout.setVerticalGroup(
            buttonbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(buttonback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(buttonclose, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonclose, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(buttonback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(5, 10, 46));
        jPanel2.setPreferredSize(new java.awt.Dimension(393, 297));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(21, 53, 84));
        jLabel5.setText("User Name:");

        jTextU_UName.setBackground(new java.awt.Color(5, 10, 46));
        jTextU_UName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextU_UName.setForeground(new java.awt.Color(255, 255, 255));
        jTextU_UName.setBorder(null);
        jTextU_UName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextU_UNameFocusGained(evt);
            }
        });
        jTextU_UName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextU_UNameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(21, 53, 84));
        jLabel6.setText("Password:");

        jTextU_Password.setBackground(new java.awt.Color(5, 10, 46));
        jTextU_Password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextU_Password.setForeground(new java.awt.Color(255, 255, 255));
        jTextU_Password.setBorder(null);
        jTextU_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextU_PasswordFocusGained(evt);
            }
        });

        butto_signup.setBackground(new java.awt.Color(5, 10, 46));
        butto_signup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        butto_signup.setForeground(new java.awt.Color(255, 255, 255));
        butto_signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/submit_progress_25px.png"))); // NOI18N
        butto_signup.setText("Submit");
        butto_signup.setBorder(null);
        butto_signup.setPreferredSize(new java.awt.Dimension(105, 33));
        butto_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butto_signupActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(21, 53, 84));
        jLabel7.setText("Name:");

        jTextU_Name.setBackground(new java.awt.Color(5, 10, 46));
        jTextU_Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextU_Name.setForeground(new java.awt.Color(255, 255, 255));
        jTextU_Name.setBorder(null);
        jTextU_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextU_NameFocusGained(evt);
            }
        });
        jTextU_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextU_NameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(21, 53, 84));
        jLabel8.setText("Confirm Password:");

        jTextU_CPassword.setBackground(new java.awt.Color(5, 10, 46));
        jTextU_CPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextU_CPassword.setForeground(new java.awt.Color(255, 255, 255));
        jTextU_CPassword.setBorder(null);
        jTextU_CPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextU_CPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextU_CPasswordFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(21, 53, 84));
        jLabel9.setText("Email:");

        jTextU_Email.setBackground(new java.awt.Color(5, 10, 46));
        jTextU_Email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextU_Email.setForeground(new java.awt.Color(255, 255, 255));
        jTextU_Email.setBorder(null);
        jTextU_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextU_EmailFocusGained(evt);
            }
        });
        jTextU_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextU_EmailActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(21, 53, 84));
        jLabel10.setText("Phone No:");

        jTextU_PNO.setBackground(new java.awt.Color(5, 10, 46));
        jTextU_PNO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextU_PNO.setForeground(new java.awt.Color(255, 255, 255));
        jTextU_PNO.setBorder(null);
        jTextU_PNO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextU_PNOFocusGained(evt);
            }
        });
        jTextU_PNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextU_PNOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextU_PNO, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(jTextU_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(jTextU_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextU_UName, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jTextU_Password)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(jTextU_CPassword)
                    .addComponent(jSeparator4)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butto_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextU_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextU_UName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextU_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextU_CPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextU_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextU_PNO, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(butto_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(432, 675));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    private void jTextU_UNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextU_UNameFocusGained
        jLabel5.setForeground(new Color(255,255,255));
        jLabel6.setForeground(new Color(21,53,84));
        jLabel7.setForeground(new Color(21,53,84));
        jLabel8.setForeground(new Color(21,53,84));
        jLabel9.setForeground(new Color(21,53,84));
        jLabel10.setForeground(new Color(21,53,84));
    }//GEN-LAST:event_jTextU_UNameFocusGained

    private void jTextU_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextU_PasswordFocusGained
        jLabel6.setForeground(new Color(255,255,255));
        jLabel5.setForeground(new Color(21,53,84));
        jLabel7.setForeground(new Color(21,53,84));
        jLabel8.setForeground(new Color(21,53,84));
        jLabel9.setForeground(new Color(21,53,84));
        jLabel10.setForeground(new Color(21,53,84));
    }//GEN-LAST:event_jTextU_PasswordFocusGained

    private void jTextU_UNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextU_UNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextU_UNameActionPerformed

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        changecolor(buttonclose, new Color(232, 17, 35));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
       changecolor(buttonclose, new Color(5, 10, 46));
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        View.View_Spare_Parts_Details E =new View.View_Spare_Parts_Details();
        E.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        changecolor(buttonback, new Color(51, 84, 158));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        changecolor(buttonback, new Color(5, 10, 46));
    }//GEN-LAST:event_backMouseExited

    private void butto_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butto_signupActionPerformed
      
        if((jTextU_Name!=null || jTextU_UName     !=null ||
                jTextU_Password !=null || jTextU_CPassword !=null ||
                jTextU_Email !=null) && jTextU_PNO != null)
        {
            try{
                Connection conn = SqlConnection();
                PreparedStatement ps = conn.prepareStatement("insert into Register" + 
                        "(FName, UName,UPassword,ConPassword,Email, PNo) values (?,?,?,?,?,?)");
                
                ps.setString(1,(jTextU_Name.getText()));
                ps.setString(2, jTextU_UName.getText());
                ps.setString(3,(jTextU_Password.getText()));
                ps.setString(4, jTextU_CPassword.getText());
                ps.setString(5, jTextU_Email.getText());
                ps.setInt(6,Integer.parseInt(jTextU_PNO.getText()));

                int res = ps.executeUpdate();
                
                if(res>=1){
                    JOptionPane.showMessageDialog(null, res + " Inserted into Dtabase");
                }
                else{
                    JOptionPane.showMessageDialog(null, " Data inserted failed");
                }
                
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                
            }
            
                jTextU_Name.setText("");
                jTextU_UName.setText("");
                jTextU_Password.setText("");
                jTextU_CPassword.setText("");
                jTextU_Email.setText("");
                jTextU_PNO.setText("");
                
        }
        else{
                    JOptionPane.showMessageDialog(null, " Data inserted failed");
                }
        
        
        
    }//GEN-LAST:event_butto_signupActionPerformed

    public void validatePassword(){
        
        String password1=jTextU_Password.getText();
        String password2=jTextU_CPassword.getText();
        
        if( !password1.equals(password2))
        {
            JOptionPane.showMessageDialog(this, "The Password does not match please check");
        }
    }
    
    
    private void jTextU_NameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextU_NameFocusGained
        jLabel7.setForeground(new Color(255,255,255));
        jLabel5.setForeground(new Color(21,53,84));
        jLabel6.setForeground(new Color(21,53,84));
        jLabel8.setForeground(new Color(21,53,84));
        jLabel9.setForeground(new Color(21,53,84));
        jLabel10.setForeground(new Color(21,53,84));
    }//GEN-LAST:event_jTextU_NameFocusGained

    private void jTextU_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextU_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextU_NameActionPerformed

    private void jTextU_CPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextU_CPasswordFocusGained
        jLabel8.setForeground(new Color(255,255,255));
        jLabel5.setForeground(new Color(21,53,84));
        jLabel6.setForeground(new Color(21,53,84));
        jLabel7.setForeground(new Color(21,53,84));
        jLabel9.setForeground(new Color(21,53,84));
        jLabel10.setForeground(new Color(21,53,84));
    }//GEN-LAST:event_jTextU_CPasswordFocusGained

    private void jTextU_EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextU_EmailFocusGained
        jLabel9.setForeground(new Color(255,255,255));
        jLabel5.setForeground(new Color(21,53,84));
        jLabel6.setForeground(new Color(21,53,84));
        jLabel7.setForeground(new Color(21,53,84));
        jLabel8.setForeground(new Color(21,53,84));
        jLabel10.setForeground(new Color(21,53,84));
    }//GEN-LAST:event_jTextU_EmailFocusGained

    private void jTextU_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextU_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextU_EmailActionPerformed

    private void jTextU_PNOFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextU_PNOFocusGained
        jLabel10.setForeground(new Color(255,255,255));
        jLabel5.setForeground(new Color(21,53,84));
        jLabel6.setForeground(new Color(21,53,84));
        jLabel7.setForeground(new Color(21,53,84));
        jLabel8.setForeground(new Color(21,53,84));
        jLabel9.setForeground(new Color(21,53,84));
    }//GEN-LAST:event_jTextU_PNOFocusGained

    private void jTextU_PNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextU_PNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextU_PNOActionPerformed

    private void jTextU_CPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextU_CPasswordFocusLost
        
        validatePassword();
        
    }//GEN-LAST:event_jTextU_CPasswordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton butto_signup;
    private javax.swing.JPanel buttonback;
    private javax.swing.JPanel buttonclose;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPasswordField jTextU_CPassword;
    private javax.swing.JTextField jTextU_Email;
    private javax.swing.JTextField jTextU_Name;
    private javax.swing.JTextField jTextU_PNO;
    private javax.swing.JPasswordField jTextU_Password;
    private javax.swing.JTextField jTextU_UName;
    // End of variables declaration//GEN-END:variables
}
