/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Interface.StockTableBean;
import Interface.Technician_Details;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DIL-SOFT 02
 */
public class View_Stock_table extends javax.swing.JFrame {

    /**
     * Creates new form SparePart_Stock_Details
     */
    
    boolean a = true;
    
    public View_Stock_table() {
        initComponents();
        dashbordview.setBackground(new Color(0,0,0,200));
        
        fillTable(); 
        
    }
    
    
        //Database connection
    public Connection SqlConnection(){
        
        Connection conn =  null;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Stock_System","root","");
            //JOptionPane.showMessageDialog(null, "Mysql connected Sucessfully");
            return conn;
            
        } catch (Exception e) {
                       JOptionPane.showMessageDialog(null, "Mysql connected fail");
            return null;
        }
    }
    
    
      //Show or add the data to the table
    public ArrayList<StockTableBean> retriveData(){
        ArrayList<StockTableBean> al=null;
        al=new ArrayList<StockTableBean>();
        
        try{
            Connection conn=SqlConnection();
            String qry="Select * from Stock_Details";
            Statement st=conn.createStatement();
            ResultSet rs= st.executeQuery(qry);
            StockTableBean Stock;
            while(rs.next()){
                Stock= new StockTableBean(rs.getInt(1), rs.getString(2),rs.getString(3), rs.getInt(4),rs.getString(5),rs.getString(6),
                        rs.getString(7));
                al.add(Stock);
            }
        }catch(Exception e){
            System.out.println("Error in retriveData method:"+e);
            
        }
       return al; 
    }
    
    public void fillTable(){
        ArrayList<StockTableBean> al = retriveData();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        
        Object[] row = new Object[7];
        for(int i=0; i<al.size(); i++){
            row[0]=al.get(i).getTid();
            row[1]=al.get(i).getTname();
            row[2]=al.get(i).getTposition();
            row[3]=al.get(i).getSid();
            row[4]=al.get(i).getSname();
            row[5]=al.get(i).getDate();
            row[6]=al.get(i).getRequirment();
            model.addRow(row);
        }
}
    
    
    //show item/data to fields:
    public void showItemToFields(int index){
        jTexttech_ID.setText(Integer.toString(retriveData().get(index).getTid()));
        jTexttech_Name.setText(retriveData().get(index).getTname());
        jTexttech_position.setText(retriveData().get(index).getTposition());
        jTextSpare_ID.setText(Integer.toString(retriveData().get(index).getSid()));
        jTextSpare_Name.setText(retriveData().get(index).getSname());
        jText_date.setText(retriveData().get(index).getDate());
        jTextArea_req.setText(retriveData().get(index).getRequirment());
        
        
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        Iconminmaxclose = new javax.swing.JPanel();
        Buttonclose = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        ButtonMax = new javax.swing.JPanel();
        Fullmax = new javax.swing.JLabel();
        ButtonMin = new javax.swing.JPanel();
        Minimize = new javax.swing.JLabel();
        Heading = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        MenuIcon = new javax.swing.JPanel();
        linehome = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        buttonhome = new javax.swing.JLabel();
        linehidemenu = new javax.swing.JPanel();
        hidemenu = new javax.swing.JPanel();
        buttonhidemenu = new javax.swing.JLabel();
        menuhide = new javax.swing.JPanel();
        buttontec_details = new javax.swing.JPanel();
        tec_details = new javax.swing.JLabel();
        buttonsparepart_details = new javax.swing.JPanel();
        sparepart_details = new javax.swing.JLabel();
        buttonuser_reg = new javax.swing.JPanel();
        user_reg = new javax.swing.JLabel();
        dashbordview = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttontsearch = new javax.swing.JPanel();
        tsearch = new javax.swing.JLabel();
        jText_Search = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jTextSpare_Name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextSpare_ID = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jTexttech_ID = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jTexttech_Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTexttech_position = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jText_date = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jTextArea_req = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(5, 10, 46));
        Header.setPreferredSize(new java.awt.Dimension(350, 50));
        Header.setLayout(new java.awt.BorderLayout());

        Iconminmaxclose.setBackground(new java.awt.Color(5, 10, 46));
        Iconminmaxclose.setPreferredSize(new java.awt.Dimension(150, 50));
        Iconminmaxclose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buttonclose.setBackground(new java.awt.Color(5, 10, 46));
        Buttonclose.setLayout(new java.awt.BorderLayout());

        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_25px.png"))); // NOI18N
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseMouseExited(evt);
            }
        });
        Buttonclose.add(Close, java.awt.BorderLayout.CENTER);

        Iconminmaxclose.add(Buttonclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        ButtonMax.setBackground(new java.awt.Color(5, 10, 46));
        ButtonMax.setPreferredSize(new java.awt.Dimension(50, 50));
        ButtonMax.setLayout(new java.awt.BorderLayout());

        Fullmax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fullmax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/full_screen_25px.png"))); // NOI18N
        Fullmax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FullmaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FullmaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FullmaxMouseExited(evt);
            }
        });
        ButtonMax.add(Fullmax, java.awt.BorderLayout.CENTER);

        Iconminmaxclose.add(ButtonMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        ButtonMin.setBackground(new java.awt.Color(5, 10, 46));
        ButtonMin.setLayout(new java.awt.BorderLayout());

        Minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize_window_25px.png"))); // NOI18N
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizeMouseExited(evt);
            }
        });
        ButtonMin.add(Minimize, java.awt.BorderLayout.CENTER);

        Iconminmaxclose.add(ButtonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        Header.add(Iconminmaxclose, java.awt.BorderLayout.LINE_END);

        Heading.setBackground(new java.awt.Color(5, 10, 46));
        Heading.setPreferredSize(new java.awt.Dimension(350, 50));
        Heading.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 1, 27)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/view_45px.png"))); // NOI18N
        jLabel8.setText("Stock Table Details");
        Heading.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, 50));

        Header.add(Heading, java.awt.BorderLayout.LINE_START);

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 50));

        menu.setPreferredSize(new java.awt.Dimension(310, 630));
        menu.setLayout(new java.awt.BorderLayout());

        MenuIcon.setBackground(new java.awt.Color(5, 10, 46));
        MenuIcon.setPreferredSize(new java.awt.Dimension(65, 630));
        MenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linehome.setBackground(new java.awt.Color(5, 10, 46));
        linehome.setPreferredSize(new java.awt.Dimension(65, 5));

        javax.swing.GroupLayout linehomeLayout = new javax.swing.GroupLayout(linehome);
        linehome.setLayout(linehomeLayout);
        linehomeLayout.setHorizontalGroup(
            linehomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        linehomeLayout.setVerticalGroup(
            linehomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(linehome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 65, 5));

        home.setBackground(new java.awt.Color(5, 10, 46));
        home.setPreferredSize(new java.awt.Dimension(65, 65));
        home.setLayout(new java.awt.BorderLayout());

        buttonhome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_30px.png"))); // NOI18N
        buttonhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhomeMouseExited(evt);
            }
        });
        home.add(buttonhome, java.awt.BorderLayout.CENTER);

        MenuIcon.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 65, 65));

        linehidemenu.setBackground(new java.awt.Color(5, 10, 46));
        linehidemenu.setPreferredSize(new java.awt.Dimension(65, 5));

        javax.swing.GroupLayout linehidemenuLayout = new javax.swing.GroupLayout(linehidemenu);
        linehidemenu.setLayout(linehidemenuLayout);
        linehidemenuLayout.setHorizontalGroup(
            linehidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        linehidemenuLayout.setVerticalGroup(
            linehidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(linehidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 65, 5));

        hidemenu.setBackground(new java.awt.Color(5, 10, 46));
        hidemenu.setPreferredSize(new java.awt.Dimension(65, 65));
        hidemenu.setLayout(new java.awt.BorderLayout());

        buttonhidemenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonhidemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_30px.png"))); // NOI18N
        buttonhidemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhidemenuMouseExited(evt);
            }
        });
        hidemenu.add(buttonhidemenu, java.awt.BorderLayout.CENTER);

        MenuIcon.add(hidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 65, 65));

        menu.add(MenuIcon, java.awt.BorderLayout.LINE_START);

        menuhide.setBackground(new java.awt.Color(25, 29, 74));

        buttontec_details.setBackground(new java.awt.Color(25, 29, 74));
        buttontec_details.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 10, 46), 1, true));
        buttontec_details.setPreferredSize(new java.awt.Dimension(170, 47));

        tec_details.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        tec_details.setForeground(new java.awt.Color(255, 255, 255));
        tec_details.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tec_details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/workers_45px.png"))); // NOI18N
        tec_details.setText("Technician Details");
        tec_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tec_detailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tec_detailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tec_detailsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttontec_detailsLayout = new javax.swing.GroupLayout(buttontec_details);
        buttontec_details.setLayout(buttontec_detailsLayout);
        buttontec_detailsLayout.setHorizontalGroup(
            buttontec_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttontec_detailsLayout.createSequentialGroup()
                .addComponent(tec_details, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        buttontec_detailsLayout.setVerticalGroup(
            buttontec_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttontec_detailsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tec_details))
        );

        buttonsparepart_details.setBackground(new java.awt.Color(25, 29, 74));
        buttonsparepart_details.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 10, 46), 1, true));

        sparepart_details.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        sparepart_details.setForeground(new java.awt.Color(255, 255, 255));
        sparepart_details.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sparepart_details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/maintenance_45px.png"))); // NOI18N
        sparepart_details.setText("Sapre Part Details");
        sparepart_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sparepart_detailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sparepart_detailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sparepart_detailsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttonsparepart_detailsLayout = new javax.swing.GroupLayout(buttonsparepart_details);
        buttonsparepart_details.setLayout(buttonsparepart_detailsLayout);
        buttonsparepart_detailsLayout.setHorizontalGroup(
            buttonsparepart_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sparepart_details, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        );
        buttonsparepart_detailsLayout.setVerticalGroup(
            buttonsparepart_detailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsparepart_detailsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sparepart_details))
        );

        buttonuser_reg.setBackground(new java.awt.Color(25, 29, 74));
        buttonuser_reg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 10, 46), 1, true));
        buttonuser_reg.setPreferredSize(new java.awt.Dimension(170, 47));

        user_reg.setFont(new java.awt.Font("Maiandra GD", 1, 16)); // NOI18N
        user_reg.setForeground(new java.awt.Color(255, 255, 255));
        user_reg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add_user_45px.png"))); // NOI18N
        user_reg.setText("User Register");
        user_reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_regMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                user_regMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                user_regMouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttonuser_regLayout = new javax.swing.GroupLayout(buttonuser_reg);
        buttonuser_reg.setLayout(buttonuser_regLayout);
        buttonuser_regLayout.setHorizontalGroup(
            buttonuser_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonuser_regLayout.createSequentialGroup()
                .addComponent(user_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        buttonuser_regLayout.setVerticalGroup(
            buttonuser_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonuser_regLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(user_reg))
        );

        javax.swing.GroupLayout menuhideLayout = new javax.swing.GroupLayout(menuhide);
        menuhide.setLayout(menuhideLayout);
        menuhideLayout.setHorizontalGroup(
            menuhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttontec_details, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
            .addComponent(buttonsparepart_details, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonuser_reg, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );
        menuhideLayout.setVerticalGroup(
            menuhideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuhideLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(buttontec_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(buttonsparepart_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(buttonuser_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        menu.add(menuhide, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 49, 290, 640));

        dashbordview.setBackground(new java.awt.Color(0, 0, 0));
        dashbordview.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dashbordview.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(55, 55, 55));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(55, 55, 55));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(55, 55, 55)));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Technician ID", "Technician Name", "Technician Position", "Spare Part ID", "Spare Part Name", "Date", "Requirment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(55, 55, 55));
        jTable1.setRowHeight(25);
        jTable1.setRowMargin(8);
        jTable1.setSelectionBackground(new java.awt.Color(110, 110, 109));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        dashbordview.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 500, 370));

        buttontsearch.setBackground(new java.awt.Color(55, 55, 55));
        buttontsearch.setPreferredSize(new java.awt.Dimension(40, 40));
        buttontsearch.setLayout(new java.awt.BorderLayout());

        tsearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_20px.png"))); // NOI18N
        tsearch.setPreferredSize(new java.awt.Dimension(35, 30));
        tsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tsearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tsearchMouseExited(evt);
            }
        });
        buttontsearch.add(tsearch, java.awt.BorderLayout.LINE_START);

        jText_Search.setBackground(new java.awt.Color(55, 55, 55));
        jText_Search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jText_Search.setForeground(new java.awt.Color(255, 255, 255));
        jText_Search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jText_Search.setPreferredSize(new java.awt.Dimension(265, 30));
        jText_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jText_SearchMousePressed(evt);
            }
        });
        jText_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jText_SearchKeyReleased(evt);
            }
        });
        buttontsearch.add(jText_Search, java.awt.BorderLayout.CENTER);

        dashbordview.add(buttontsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 300, 30));
        dashbordview.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 300, 10));
        dashbordview.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 260, -1));

        jTextSpare_Name.setBackground(new java.awt.Color(55, 55, 55));
        jTextSpare_Name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextSpare_Name.setForeground(new java.awt.Color(255, 255, 255));
        jTextSpare_Name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextSpare_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextSpare_Name.setCaretColor(new java.awt.Color(55, 55, 55));
        jTextSpare_Name.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTextSpare_Name.setSelectionColor(new java.awt.Color(55, 55, 55));
        dashbordview.add(jTextSpare_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 260, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Spare Part Name:");
        dashbordview.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 30));

        jTextSpare_ID.setBackground(new java.awt.Color(55, 55, 55));
        jTextSpare_ID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextSpare_ID.setForeground(new java.awt.Color(255, 255, 255));
        jTextSpare_ID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextSpare_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextSpare_ID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextSpare_ID.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTextSpare_ID.setSelectionColor(new java.awt.Color(55, 55, 55));
        jTextSpare_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextSpare_IDKeyPressed(evt);
            }
        });
        dashbordview.add(jTextSpare_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 260, 30));
        dashbordview.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 260, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Spare Part ID:");
        dashbordview.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 110, 30));

        jTexttech_ID.setBackground(new java.awt.Color(55, 55, 55));
        jTexttech_ID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTexttech_ID.setForeground(new java.awt.Color(255, 255, 255));
        jTexttech_ID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTexttech_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTexttech_ID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTexttech_ID.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTexttech_ID.setSelectionColor(new java.awt.Color(55, 55, 55));
        jTexttech_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTexttech_IDKeyPressed(evt);
            }
        });
        dashbordview.add(jTexttech_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 260, 30));
        dashbordview.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 260, 10));

        jTexttech_Name.setBackground(new java.awt.Color(55, 55, 55));
        jTexttech_Name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTexttech_Name.setForeground(new java.awt.Color(255, 255, 255));
        jTexttech_Name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTexttech_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTexttech_Name.setCaretColor(new java.awt.Color(55, 55, 55));
        jTexttech_Name.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTexttech_Name.setSelectionColor(new java.awt.Color(55, 55, 55));
        dashbordview.add(jTexttech_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 260, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Technician ID:");
        dashbordview.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 100, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Technician Name:");
        dashbordview.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 130, 30));

        jTexttech_position.setBackground(new java.awt.Color(55, 55, 55));
        jTexttech_position.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTexttech_position.setForeground(new java.awt.Color(255, 255, 255));
        jTexttech_position.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTexttech_position.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTexttech_position.setCaretColor(new java.awt.Color(55, 55, 55));
        jTexttech_position.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jTexttech_position.setSelectionColor(new java.awt.Color(55, 55, 55));
        jTexttech_position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexttech_positionActionPerformed(evt);
            }
        });
        dashbordview.add(jTexttech_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 260, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Technician Position:");
        dashbordview.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date:");
        dashbordview.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 50, 30));

        jText_date.setBackground(new java.awt.Color(55, 55, 55));
        jText_date.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jText_date.setForeground(new java.awt.Color(255, 255, 255));
        jText_date.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jText_date.setText("DD-MM-YYYY");
        jText_date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jText_date.setCaretColor(new java.awt.Color(55, 55, 55));
        jText_date.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jText_date.setSelectionColor(new java.awt.Color(55, 55, 55));
        dashbordview.add(jText_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 260, 30));
        dashbordview.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 260, 10));
        dashbordview.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 260, -1));

        jTextArea_req.setBackground(new java.awt.Color(55, 55, 55));
        jTextArea_req.setColumns(20);
        jTextArea_req.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextArea_req.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_req.setRows(5);
        jTextArea_req.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dashbordview.add(jTextArea_req, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Requirment:");
        dashbordview.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 100, 30));

        getContentPane().add(dashbordview, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 980, 590));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DIL-SOFT 02\\Documents\\NetBeansProjects\\Spare Part\\src\\Images\\Image 2.jpg")); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 980, 640));

        setSize(new java.awt.Dimension(1266, 642));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void changercolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    
    public void clickmenu(JPanel h1, JPanel h2, int numberbool){
       if(numberbool == 1){
           h1.setBackground(new Color(25, 29, 74));
           h2.setBackground(new Color(5, 10, 46));
       } 
       else{
           h1.setBackground(new Color(5, 10, 46));
           h2.setBackground(new Color(25, 29, 74));
       }
    }
  
    
    
    //method for change image
    public void changeImage (JLabel button, String resourcheimg){
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
        button.setIcon(aimg);
    } 
    
    
    //menu
    public void hideshow(JPanel menushowhide, boolean dashboard, JLabel button){
        if(dashboard == true){
            menushowhide.setPreferredSize(new Dimension(65, menushowhide.getHeight()));
            changeImage(button,"/Images/menu_30px.png");
        }
        else{
            menushowhide.setPreferredSize(new Dimension(276, menushowhide.getHeight()));
            changeImage(button,"/Images/back_30px.png");
        }
    }
    
    private void CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseEntered
        changercolor(Buttonclose, new Color (232, 17, 35));
    }//GEN-LAST:event_CloseMouseEntered

    private void CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseExited
        changercolor(Buttonclose, new Color (5, 10, 46));
    }//GEN-LAST:event_CloseMouseExited

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void FullmaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullmaxMouseEntered
        changercolor(ButtonMax, new Color (25, 29, 74));
    }//GEN-LAST:event_FullmaxMouseEntered

    private void FullmaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullmaxMouseExited
        changercolor(ButtonMax, new Color (5, 10, 46));
    }//GEN-LAST:event_FullmaxMouseExited

    private void FullmaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullmaxMouseClicked
        if(this.getExtendedState()!= View_Stock_table.MAXIMIZED_BOTH )
        {
            this.setExtendedState(View_Stock_table.MAXIMIZED_BOTH);
        }
        else{
            this.setExtendedState(View_Stock_table.NORMAL);
        }
    }//GEN-LAST:event_FullmaxMouseClicked

    private void buttonhidemenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseEntered
        changercolor(linehidemenu, new Color (247,78,105));
    }//GEN-LAST:event_buttonhidemenuMouseEntered

    private void buttonhidemenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseExited
        changercolor(linehidemenu, new Color (5, 10, 46));
    }//GEN-LAST:event_buttonhidemenuMouseExited

    private void buttonhidemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhidemenuMouseClicked
       clickmenu(hidemenu, home, 1);
       
       //create void for method hide and show panel menu
       if(a==true){
           hideshow(menu , a, buttonhidemenu);
           SwingUtilities.updateComponentTreeUI(this);
           a=false;
       }
       else{
           hideshow(menu , a, buttonhidemenu);
           SwingUtilities.updateComponentTreeUI(this);
           a=true;
       }
       
    }//GEN-LAST:event_buttonhidemenuMouseClicked

    private void MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseEntered
        changercolor(ButtonMin, new Color (25, 29, 74));
    }//GEN-LAST:event_MinimizeMouseEntered

    private void MinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseExited
        changercolor(ButtonMin, new Color (5, 10, 46));
    }//GEN-LAST:event_MinimizeMouseExited

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        
    }//GEN-LAST:event_MinimizeMouseClicked

    private void buttonhomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhomeMouseEntered
       changercolor(linehome, new Color (8, 177, 150));
       changercolor(home, new Color (25,29,74));
    }//GEN-LAST:event_buttonhomeMouseEntered

    private void buttonhomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhomeMouseExited
        changercolor(linehome, new Color (5, 10, 46));
        changercolor(home, new Color (5, 10, 46));
    }//GEN-LAST:event_buttonhomeMouseExited

    private void buttonhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhomeMouseClicked
        clickmenu(home, hidemenu, 1);
        
        Interface.Home E =new Interface.Home();
        E.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonhomeMouseClicked

    private void tec_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tec_detailsMouseClicked
        View.View_Technician_Details E =new View.View_Technician_Details();
        E.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tec_detailsMouseClicked

    private void tec_detailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tec_detailsMouseEntered
        changercolor(buttontec_details, new Color (145, 145, 146));
    }//GEN-LAST:event_tec_detailsMouseEntered

    private void tec_detailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tec_detailsMouseExited
        changercolor(buttontec_details, new Color (25,29,74));
    }//GEN-LAST:event_tec_detailsMouseExited

    private void sparepart_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sparepart_detailsMouseClicked
        View.View_Spare_Parts_Details E =new View.View_Spare_Parts_Details();
        E.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sparepart_detailsMouseClicked

    private void sparepart_detailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sparepart_detailsMouseEntered
        changercolor(buttonsparepart_details, new Color (145, 145, 146));
    }//GEN-LAST:event_sparepart_detailsMouseEntered

    private void sparepart_detailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sparepart_detailsMouseExited
        changercolor(buttonsparepart_details, new Color (25,29,74));
    }//GEN-LAST:event_sparepart_detailsMouseExited

    private void tsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsearchMouseClicked

    }//GEN-LAST:event_tsearchMouseClicked

    private void tsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsearchMouseEntered
        changercolor(buttontsearch, new Color (110, 110, 109));
    }//GEN-LAST:event_tsearchMouseEntered

    private void tsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tsearchMouseExited
        changercolor(buttontsearch, new Color (55,55,55));
    }//GEN-LAST:event_tsearchMouseExited

    private void jText_SearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jText_SearchMousePressed

    }//GEN-LAST:event_jText_SearchMousePressed

    private void jText_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_SearchKeyReleased

        ArrayList<StockTableBean> al = null;
        al= new ArrayList<StockTableBean>();
        String val=jText_Search.getText().toString();

        try{
            Connection conn=SqlConnection();

            String qry="select * from Stock_Details where Tech_Name '%"+val+"%'";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(qry);
            StockTableBean Stock;
            while(rs.next()){
                Stock= new StockTableBean(rs.getInt(1), rs.getString(2),rs.getString(3), rs.getInt(4),rs.getString(5),rs.getString(6),
                    rs.getString(7));
                al.add(Stock);
            }

            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);

            Object[] row = new Object[7];
            for(int i=0; i<al.size(); i++){
                row[0]=al.get(i).getTid();
                row[1]=al.get(i).getTname();
                row[2]=al.get(i).getTposition();
                row[3]=al.get(i).getSid();
                row[4]=al.get(i).getSname();
                row[5]=al.get(i).getDate();
                row[6]=al.get(i).getRequirment();
                model.addRow(row);
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jText_SearchKeyReleased

    private void user_regMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_regMouseClicked
        User_RegisterForm E =new User_RegisterForm();
        E.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_user_regMouseClicked

    private void user_regMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_regMouseEntered
        changercolor(buttonuser_reg, new Color (145, 145, 146));
    }//GEN-LAST:event_user_regMouseEntered

    private void user_regMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_regMouseExited
        changercolor(buttonuser_reg, new Color (25,29,74));
    }//GEN-LAST:event_user_regMouseExited

    private void jTextSpare_IDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSpare_IDKeyPressed

    }//GEN-LAST:event_jTextSpare_IDKeyPressed

    private void jTexttech_IDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexttech_IDKeyPressed

    }//GEN-LAST:event_jTexttech_IDKeyPressed

    private void jTexttech_positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexttech_positionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexttech_positionActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int ind=jTable1.getSelectedRow();
        showItemToFields(ind);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Stock_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Stock_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Stock_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Stock_table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Stock_table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonMax;
    private javax.swing.JPanel ButtonMin;
    private javax.swing.JPanel Buttonclose;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Fullmax;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Heading;
    private javax.swing.JPanel Iconminmaxclose;
    private javax.swing.JPanel MenuIcon;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel buttonhidemenu;
    private javax.swing.JLabel buttonhome;
    private javax.swing.JPanel buttonsparepart_details;
    private javax.swing.JPanel buttontec_details;
    private javax.swing.JPanel buttontsearch;
    private javax.swing.JPanel buttonuser_reg;
    private javax.swing.JPanel dashbordview;
    private javax.swing.JPanel hidemenu;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea_req;
    private javax.swing.JTextField jTextSpare_ID;
    private javax.swing.JTextField jTextSpare_Name;
    private javax.swing.JTextField jText_Search;
    private javax.swing.JTextField jText_date;
    private javax.swing.JTextField jTexttech_ID;
    private javax.swing.JTextField jTexttech_Name;
    private javax.swing.JTextField jTexttech_position;
    private javax.swing.JPanel linehidemenu;
    private javax.swing.JPanel linehome;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuhide;
    private javax.swing.JLabel sparepart_details;
    private javax.swing.JLabel tec_details;
    private javax.swing.JLabel tsearch;
    private javax.swing.JLabel user_reg;
    // End of variables declaration//GEN-END:variables

}
    
